# Generated by Django 3.1.5 on 2021-01-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to='uploads/% Y/% m/% d/')),
                ('file_size', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
