# Generated by Django 2.1.5 on 2021-01-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210124_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='status',
        ),
    ]
