# Generated by Django 2.1.5 on 2021-01-24 22:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('subscriptions', '0004_remove_new_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
