# Generated by Django 2.0.8 on 2021-01-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_new_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
